In [4]:
import numpy as np
from numpy import random

random.rand(5,5)

array([[2.46576199e-01, 2.50622187e-01, 8.11178851e-01, 4.72012640e-01,
        7.42188550e-01],
       [8.70817010e-01, 7.81530738e-01, 2.65296229e-01, 9.88490147e-02,
        6.15643188e-01],
       [9.10836545e-01, 6.90095800e-01, 9.26064657e-01, 6.57057760e-01,
        3.40746595e-01],
       [9.34680164e-01, 7.72677375e-01, 2.55781280e-04, 4.04056619e-01,
        1.02442862e-01],
       [9.62390746e-01, 9.75607612e-01, 7.73461590e-02, 7.07944172e-01,
        2.60762028e-01]])

In [8]:
x = random.randn(5,5)
x

array([[ 0.22299584,  1.05715072,  1.5013098 , -1.05277236, -1.23013833],
       [-0.06479841,  1.79418785,  0.5510427 , -0.70448833, -1.26463339],
       [-0.43585344,  1.22897844,  0.05729665,  0.72125005,  1.72033892],
       [ 1.04606496, -1.22045241,  0.82313814, -0.29336664, -0.37895849],
       [ 0.75425243, -0.26253732,  0.08038932,  0.58697981, -0.98069696]])

Exercise 2

1. Generate a 1-D array containing 5 random integers from 0 to 100
2. Generate a 2-D array with 3 rows, each row contains 5 random integers from 0 to 100
3. Generate a 1-D array of 30 evenly spaced element 1.5 and 5.5 inclusive.

In [23]:
a1 = random.randint(0,100,size = 5)
a1

array([39, 54, 18, 13, 93])

In [13]:
a2 = random.randint(0,100,size=(3,5))
a2

array([[97, 14,  1, 59, 83],
       [ 5, 29, 35, 18,  5],
       [68, 75, 63, 60, 59]])

In [15]:
a3 = np.linspace(1.5,5.5,30, dtype=float)
a3

array([1.5       , 1.63793103, 1.77586207, 1.9137931 , 2.05172414,
       2.18965517, 2.32758621, 2.46551724, 2.60344828, 2.74137931,
       2.87931034, 3.01724138, 3.15517241, 3.29310345, 3.43103448,
       3.56896552, 3.70689655, 3.84482759, 3.98275862, 4.12068966,
       4.25862069, 4.39655172, 4.53448276, 4.67241379, 4.81034483,
       4.94827586, 5.0862069 , 5.22413793, 5.36206897, 5.5       ])

Exercise 3

In [31]:
b1 = random.randint(2,10, size = 9)
b1.reshape(3,3)

array([[3, 7, 6],
       [7, 5, 8],
       [5, 5, 6]])

In [34]:
x1 = np.arange(2,11).reshape(3,3)
x1

array([[ 2,  3,  4],
       [ 5,  6,  7],
       [ 8,  9, 10]])

In [36]:
y1 = np.array([[0,1,3],[5,7,9]])
y2 = np.array([[0,2,4],[6,8,10]])
y3 = np.concatenate((y1,y2),axis = 1)
y3

array([[ 0,  1,  3,  0,  2,  4],
       [ 5,  7,  9,  6,  8, 10]])

Indexing and Slicing

In [40]:
data = np.array([1,2,3,4,5])
data[3:]

array([4, 5])

In [56]:
x = np.array([3,2,3,4,5,6,7,7,8,10,11,23,34],dtype=int)
m = np.hsplit(x,(2,4))
m

[array([3, 2]), array([3, 4]), array([ 5,  6,  7,  7,  8, 10, 11, 23, 34])]

Exercise 4

1. create a null vector / 1D array of size 10 and update fifth value to 11.

In [12]:
import numpy as np
x = np.zeros(10)
print(x)

x[5] = 11
print(x)


[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[ 0.  0.  0.  0.  0. 11.  0.  0.  0.  0.]


2. Write a NumPy program to create a 2x3 arrays and change it into 3x2 arrays

In [33]:
from numpy import random

x = random.randint(1, 10, size=(2,3))
print(x)
print("--------------")
x = np.reshape(x,(3,2))
print(x)

[[6 2 7]
 [5 4 8]]
--------------
[[6 2]
 [7 5]
 [4 8]]


3. Write a NumPy program to create a 2d array with 1 on the border and 0 inside. 

In [44]:
x = np.ones((5,5))
print(x)
print("1 on the border and 0 inside in the array")
x[1:-1,1:-1] = 0
print(x)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
1 on the border and 0 inside in the array
[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


4. Take a look at the following matrix. Access the [2, 1,1]

In [59]:
z = np.array([[[0, 1, 3],
               [5, 7, 9],
               [6, 8, 10]],
              
              [[0, 2, 4],
               [6, 8, 10],
               [0, 1, 3]],
             
              [[1, 1, 2],
               [5, 2, 9],
               [1, 3, 3]]])

z[2,1,1]


2

ASSIGNMENT

1. Create a 4x4 matrix with values ranging from 0 to 3.
(The following image is just as an example. It doesn't represent the real image of arrays in the question) 

In [62]:
x = np.zeros((4,4))
print(x)
print("----------------")
x += np.arange(4)
print(x)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
----------------
[[0. 1. 2. 3.]
 [0. 1. 2. 3.]
 [0. 1. 2. 3.]
 [0. 1. 2. 3.]]


2. Create and array with shape of 4x4 and turn it into two arrays along the second axis.

In [71]:
x = np.arange(16).reshape((4, 4))
print(x)
print("----------------")
x= np.hsplit(x, [2, 6])
print(x)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
----------------
[array([[ 0,  1],
       [ 4,  5],
       [ 8,  9],
       [12, 13]]), array([[ 2,  3],
       [ 6,  7],
       [10, 11],
       [14, 15]]), array([], shape=(4, 0), dtype=int32)]
